import { Poppins } from 'next/font/google';

import { AppProviders } from '@/providers/AppProviders';

import type { ReactNode } from 'react';

import '@/styles/globals.css';

const poppins = Poppins({
	variable: '--font-poppins',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({
	children,
}: {
	readonly children: ReactNode;
}) {
	return (
		<html lang="en" className={poppins.variable}>
			<head>
				<title>Mobius</title>
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				<AppProviders>{children}</AppProviders>
			</body>
		</html>
	);
}
