import '@/styles/globals.css';

import { Poppins } from '@next/font/google';
import type { ReactNode } from 'react';

const poppins = Poppins({
	variable: '--font-poppins',
	weight: ['400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({
	children,
}: {
	readonly children: ReactNode;
}) {
	return (
		<html lang="en" className={poppins.variable}>
			<head>
				<title>Mobius</title>
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>{children}</body>
		</html>
	);
}
